version: '2.3'
services:
  demo:
    build:
      context: ./
      dockerfile: Dockerfile
    image: demomavenapp
    ports:
      - 9092
    networks:
      - network1
    scale: 3

networks:
  network1: